using System.Globalization;
using Kkdev92.Jev.CodeGen.Commands;
using Kkdev92.Jev.CodeGen.CSharp;
using Kkdev92.Jev.CodeGen.Specifications;

namespace Kkdev92.Jev.CodeGen.Tests;

/// <summary>The same snapshot always produces the same bytes, and the committed sources are those bytes.</summary>
public sealed class GeneratorTests
{
    private static SortedDictionary<string, string> Generate() => GenerateCommand.Produce(SpecFixture.Layout, RepositoryLayout.DefaultContract).Files;

    [Fact]
    public void TheCommittedSourcesAreCurrent()
    {
        var problems = GenerateCommand.Compare(SpecFixture.Layout.GeneratedRoot, Generate());
        Assert.True(problems.Count == 0, "Run 'codegen generate': " + string.Join("; ", problems));
    }

    /// <summary>Two runs in one process: a dependence on dictionary enumeration order would show here.</summary>
    [Fact]
    public void GeneratingTwiceProducesIdenticalOutput() => Assert.Equal(Generate(), Generate());

    [Theory]
    [InlineData("tr-TR")]
    [InlineData("ja-JP")]
    [InlineData("ar-SA")]
    [InlineData("de-DE")]
    public void TheOutputDoesNotDependOnTheCulture(string culture)
    {
        var expected = Generate();
        var (current, currentUi) = (CultureInfo.CurrentCulture, CultureInfo.CurrentUICulture);

        try
        {
            CultureInfo.CurrentCulture = CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo(culture);
            Assert.Equal(expected, Generate());
        }
        finally
        {
            (CultureInfo.CurrentCulture, CultureInfo.CurrentUICulture) = (current, currentUi);
        }
    }

    [Fact]
    public void EveryFileIsAsciiLfAndEndsWithANewline()
    {
        foreach (var (path, content) in Generate())
        {
            Assert.True(content.All(c => c < 0x80), $"{path} contains a non-ASCII character.");
            Assert.DoesNotContain('\r', content);
            Assert.EndsWith("\n", content, StringComparison.Ordinal);
            Assert.EndsWith(".g.cs", path, StringComparison.Ordinal);
        }
    }

    [Fact]
    public void NothingRecordsWhenOrWhereItWasGenerated()
    {
        var retrievedAt = SpecFixture.Committed().Provenance.RetrievedAtUtc;

        foreach (var (path, content) in Generate())
        {
            Assert.DoesNotContain(retrievedAt[..10], content, StringComparison.Ordinal);
            Assert.DoesNotContain(SpecFixture.Layout.Root, content, StringComparison.OrdinalIgnoreCase);
            Assert.StartsWith("// <auto-generated />\n", content, StringComparison.Ordinal);
            Assert.Contains($"// Spec SHA-256: {SpecFixture.Committed().Provenance.Snapshot.Sha256}\n", content, StringComparison.Ordinal);
            Assert.Contains($"// Generator: {CSharpEmitter.GeneratorVersion}\n", content, StringComparison.Ordinal);
            Assert.False(string.IsNullOrEmpty(path));
        }
    }

    [Fact]
    public void NoUpstreamProseReachesTheGeneratedCode()
    {
        // Descriptions are TypeSafe's text; the generator emits structure only.
        var generated = string.Concat(Generate().Values);

        Assert.DoesNotContain("probability-weighted average", generated, StringComparison.Ordinal);
        Assert.DoesNotContain("Human-readable", generated, StringComparison.Ordinal);
    }

    [Fact]
    public void TheOutputIsTheExpectedSet()
    {
        var files = Generate().Keys.ToList();

        Assert.Equal(18, files.Count);
        Assert.Contains("JevContract.g.cs", files);
        Assert.Contains("JevWireJsonContext.g.cs", files);
        Assert.Contains("Wire/SystemOneRequest.g.cs", files);
        Assert.Contains("Wire/HttpValidationError.g.cs", files);
    }

    [Fact]
    public void VerifyNoticesMissingStaleAndOrphanedFiles()
    {
        var expected = Generate();
        var root = Path.Combine(Path.GetTempPath(), "jev-codegen-" + Guid.NewGuid().ToString("N"));

        try
        {
            foreach (var (relative, content) in expected)
            {
                var path = Path.Combine(root, relative.Replace('/', Path.DirectorySeparatorChar));
                Directory.CreateDirectory(Path.GetDirectoryName(path)!);
                File.WriteAllBytes(path, JsonCanonicalizer.Encoding.GetBytes(content));
            }

            Assert.Empty(GenerateCommand.Compare(root, expected));

            File.Delete(Path.Combine(root, "Wire", "Usage.g.cs"));
            File.AppendAllText(Path.Combine(root, "JevContract.g.cs"), "// edited\n");
            File.WriteAllText(Path.Combine(root, "Wire", "Removed.g.cs"), "// left behind\n");

            var problems = GenerateCommand.Compare(root, expected);

            Assert.Contains(problems, p => p.StartsWith("missing", StringComparison.Ordinal) && p.EndsWith("Wire/Usage.g.cs", StringComparison.Ordinal));
            Assert.Contains(problems, p => p.StartsWith("stale", StringComparison.Ordinal) && p.EndsWith("JevContract.g.cs", StringComparison.Ordinal));
            Assert.Contains(problems, p => p.StartsWith("orphan", StringComparison.Ordinal) && p.EndsWith("Wire/Removed.g.cs", StringComparison.Ordinal));
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }
}
