using System.Globalization;
using System.Text.RegularExpressions;
using Kkdev92.Jev.CodeGen.IntermediateModel;
using Kkdev92.Jev.CodeGen.Normalization;
using Kkdev92.Jev.CodeGen.Validation;

namespace Kkdev92.Jev.CodeGen.CSharp;

/// <summary>
/// Emits the generated sources: one wire model per reachable schema, the serializer context, and
/// the contract constants.
/// </summary>
/// <remarks>
/// <para>
/// The emitter never reads the OpenAPI document. It receives the validated intermediate model, so
/// everything it can produce has already been through the parser's allowlist.
/// </para>
/// <para>
/// Descriptions and examples from the document are not emitted. The wire models are internal and
/// document nothing a consumer reads, and not reproducing TypeSafe's prose keeps the generated
/// code free of text this repository has no licence to relicense.
/// </para>
/// <para>
/// Output must be byte-identical for identical input: no timestamp, no machine path, no culture,
/// no enumeration order that is not sorted first.
/// </para>
/// </remarks>
internal static partial class CSharpEmitter
{
    /// <summary>Bumped by hand when a change to this emitter changes its output.</summary>
    public const int GeneratorVersion = 2;

    public const string Namespace = "Kkdev92.Jev.Wire";
    public const string ContextName = "JevWireJsonContext";
    public const string ContractClassName = "JevContract";

    /// <summary>Emits every generated file, keyed by path relative to the generated root, with '/' separators.</summary>
    public static SortedDictionary<string, string> Emit(ValidatedContract validated)
    {
        var contract = validated.Contract;
        var header = Header(contract);
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal);

        foreach (var schema in validated.ReachableSchemas)
        {
            var writer = new CodeWriter();
            WritePreamble(writer, header);

            switch (schema)
            {
                case UnionSchemaDef union:
                    WriteUnion(writer, union, contract);
                    break;
                case ObjectSchemaDef obj:
                    WriteObject(writer, obj, contract);
                    break;
            }

            files.Add($"Wire/{schema.CSharpName}.g.cs", writer.ToString());
        }

        files.Add($"{ContextName}.g.cs", WriteContext(validated, header));
        files.Add($"{ContractClassName}.g.cs", WriteContract(validated, header));

        return files;
    }

    private static string Header(ApiContract contract)
    {
        // Everything interpolated into a comment is checked for shape first, so that nothing taken
        // from the document can close the comment or start a directive.
        Require(SafeToken().IsMatch(contract.Contract), "contract name", contract.Contract);
        Require(SafeToken().IsMatch(contract.OpenApiVersion), "OpenAPI version", contract.OpenApiVersion);
        Require(SafeToken().IsMatch(contract.ApiVersion), "API version", contract.ApiVersion);
        Require(Sha256().IsMatch(contract.SnapshotSha256), "SHA-256", contract.SnapshotSha256);

        return string.Join('\n',
            "// <auto-generated />",
            $"// Generated by Kkdev92.Jev.CodeGen from spec/{contract.Contract}. Do not edit: change the",
            "// specification or the generator, then run 'codegen generate'.",
            $"// Contract: {contract.Contract}, OpenAPI {contract.OpenApiVersion}, API version {contract.ApiVersion}",
            $"// Spec SHA-256: {contract.SnapshotSha256}",
            $"// Generator: {GeneratorVersion.ToString(CultureInfo.InvariantCulture)}");
    }

    private static void WritePreamble(CodeWriter writer, string header)
    {
        foreach (var line in header.Split('\n'))
        {
            writer.Line(line);
        }

        writer.Line();
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("using System.Collections.Generic;");
        writer.Line("using System.Text.Json;");
        writer.Line("using System.Text.Json.Serialization;");
        writer.Line("using Kkdev92.Jev.Serialization;");
        writer.Line();
        writer.Line($"namespace {Namespace};");
        writer.Line();
    }

    private static void WriteUnion(CodeWriter writer, UnionSchemaDef union, ApiContract contract)
    {
        writer.Line($"/// <summary>The <c>{union.WireName}</c> union, told apart by <c>{Xml(union.DiscriminatorProperty)}</c>.</summary>");
        writer.Line($"[JsonPolymorphic(TypeDiscriminatorPropertyName = {CodeWriter.Literal(union.DiscriminatorProperty)}, UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FailSerialization)]");

        foreach (var member in union.Members.OrderBy(m => m.Tag, StringComparer.Ordinal))
        {
            writer.Line($"[JsonDerivedType(typeof({contract.Schema(member.SchemaWireName).CSharpName}), {CodeWriter.Literal(member.Tag)})]");
        }

        writer.Open($"internal abstract class {union.CSharpName}");
        writer.Line("/// <summary>Checks what the serializer does not: value kinds, minimum counts, finite numbers, null entries.</summary>");
        writer.Line("internal abstract void Validate(WireValidation validation, string path);");
        writer.Close();
    }

    private static void WriteObject(CodeWriter writer, ObjectSchemaDef obj, ApiContract contract)
    {
        var baseClass = obj.Union is { } union ? " : " + contract.Schema(union).CSharpName : string.Empty;

        writer.Line($"/// <summary>The <c>{obj.WireName}</c> schema.</summary>");
        writer.Open($"internal sealed class {obj.CSharpName}{baseClass}");

        var emitted = obj.Properties.Where(p => p.Type is not ConstRef).OrderBy(p => p.CSharpName, StringComparer.Ordinal).ToList();

        foreach (var property in emitted)
        {
            WriteProperty(writer, property, contract);
            writer.Line();
        }

        var modifier = obj.Union is null ? "internal void" : "internal override void";
        writer.Line("/// <summary>Checks what the serializer does not: value kinds, minimum counts, finite numbers, null entries.</summary>");
        writer.Open($"{modifier} Validate(WireValidation validation, string path)");

        foreach (var property in emitted)
        {
            var member = $"WireValidation.Member(path, {CodeWriter.Literal(property.WireName)})";
            WriteValidation(writer, property.CSharpName, property.Type, property.Required, member, contract, depth: 0);
        }

        writer.Close();
        writer.Close();
    }

    private static void WriteProperty(CodeWriter writer, PropertyDef property, ApiContract contract)
    {
        writer.Line($"[JsonPropertyName({CodeWriter.Literal(property.WireName)})]");

        if (property.Required)
        {
            writer.Line("[JsonRequired]");
        }
        else
        {
            // Absent stays absent on the way out. For a JsonElement "absent" is default(JsonElement),
            // which is Undefined; an explicit JSON null is a JsonElement of kind Null and is written.
            writer.Line(property.Type is JsonValueRef
                ? "[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]"
                : "[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]");
        }

        if (property.Type is PrimitiveRef { Kind: PrimitiveKind.Integer })
        {
            if (!property.Required)
            {
                throw new InvalidDataException($"'{Naming.Printable(property.WireName)}': an optional integer is not supported; nothing in the contract has needed one.");
            }

            // A token count is an exact integer and must never pass through double on the way to
            // long. The converter accepts 120 and 120.0 and 1.2e2, and refuses 120.5.
            writer.Line("[JsonConverter(typeof(JsonExactInt64Converter))]");
        }

        var type = TypeName(property.Type, contract);
        var nullable = property.Required || property.Type is JsonValueRef ? type : type + "?";

        if (property.Type is NullableRef)
        {
            nullable = type + "?";
        }

        var initializer = property.Required && IsReference(property.Type) && property.Type is not NullableRef ? " = null!;" : string.Empty;

        writer.Line($"public {nullable} {property.CSharpName} {{ get; set; }}{initializer}");
    }

    private static void WriteValidation(CodeWriter writer, string access, TypeRef type, bool required, string path, ApiContract contract, int depth)
    {
        switch (type)
        {
            case JsonValueRef value:
                writer.Line(required
                    ? $"validation.Kinds({access}, {Kinds(value.Kinds)}, {path});"
                    : $"validation.OptionalKinds({access}, {Kinds(value.Kinds)}, {path});");
                break;

            case PrimitiveRef { Kind: PrimitiveKind.Number }:
                writer.Line(required
                    ? $"validation.Finite({access}, {path});"
                    : $"if ({access} is {{ }} v{depth}) validation.Finite(v{depth}, {path});");
                break;

            case PrimitiveRef:
                break;

            case SchemaRef:
                writer.Line(required
                    ? $"{access}.Validate(validation, {path});"
                    : $"{access}?.Validate(validation, {path});");
                break;

            case NullableRef:
                writer.Line($"{access}?.Validate(validation, {path});");
                break;

            case MapRef map:
                {
                    var target = required ? access : $"m{depth}";

                    if (!required)
                    {
                        writer.Open($"if ({access} is {{ }} {target})");
                    }

                    if (map.MinProperties is { } min)
                    {
                        writer.Line($"validation.MinCount({target}.Count, {min.ToString(CultureInfo.InvariantCulture)}, {path});");
                    }

                    writer.Open($"foreach (var e{depth} in {target})");
                    var entryPath = $"WireValidation.Key({path}, e{depth}.Key)";
                    WriteElementValidation(writer, $"e{depth}.Value", map.Value, entryPath, contract, depth + 1);
                    writer.Close();

                    if (!required)
                    {
                        writer.Close();
                    }

                    break;
                }

            case ArrayRef array:
                {
                    var target = required ? access : $"a{depth}";

                    if (!required)
                    {
                        writer.Open($"if ({access} is {{ }} {target})");
                    }

                    if (array.MinItems is { } min)
                    {
                        writer.Line($"validation.MinCount({target}.Count, {min.ToString(CultureInfo.InvariantCulture)}, {path});");
                    }

                    writer.Open($"for (var i{depth} = 0; i{depth} < {target}.Count; i{depth}++)");
                    var itemPath = $"WireValidation.Index({path}, i{depth})";
                    WriteElementValidation(writer, $"{target}[i{depth}]", array.Items, itemPath, contract, depth + 1);
                    writer.Close();

                    if (!required)
                    {
                        writer.Close();
                    }

                    break;
                }

            case ConstRef:
                break;

            default:
                throw new InvalidOperationException($"No validation for {type}.");
        }
    }

    /// <summary>
    /// Validation for a map value or an array item. The serializer's nullability checks cover
    /// properties only, not the elements of a collection, so a null element is caught here.
    /// </summary>
    private static void WriteElementValidation(CodeWriter writer, string access, TypeRef type, string path, ApiContract contract, int depth)
    {
        switch (type)
        {
            case SchemaRef:
                writer.Line($"if ({access} is null) validation.Null({path}); else {access}.Validate(validation, {path});");
                break;

            case PrimitiveRef { Kind: PrimitiveKind.String }:
                writer.Line($"if ({access} is null) validation.Null({path});");
                break;

            case PrimitiveRef { Kind: PrimitiveKind.Integer }:
                throw new InvalidDataException("An integer inside a collection is not supported; nothing in the contract has needed one.");

            default:
                WriteValidation(writer, access, type, required: true, path, contract, depth);
                break;
        }
    }

    private static string TypeName(TypeRef type, ApiContract contract) => type switch
    {
        PrimitiveRef { Kind: PrimitiveKind.String } => "string",
        PrimitiveRef { Kind: PrimitiveKind.Number } => "double",
        PrimitiveRef { Kind: PrimitiveKind.Integer } => "long",
        SchemaRef s => contract.Schema(s.WireName).CSharpName,
        NullableRef n => contract.Schema(n.Inner.WireName).CSharpName,
        MapRef m => $"Dictionary<string, {TypeName(m.Value, contract)}>",
        ArrayRef a => $"List<{TypeName(a.Items, contract)}>",
        JsonValueRef => "JsonElement",
        _ => throw new InvalidOperationException($"No C# type for {type}."),
    };

    private static bool IsReference(TypeRef type) => type is PrimitiveRef { Kind: PrimitiveKind.String } or SchemaRef or NullableRef or MapRef or ArrayRef;

    private static string Kinds(JsonKinds kinds)
    {
        var names = Enum.GetValues<JsonKinds>()
            .Where(k => k is not (JsonKinds.None or JsonKinds.Any) && kinds.HasFlag(k))
            .Select(k => "JsonKinds." + k);

        return kinds == JsonKinds.Any ? "JsonKinds.Any" : string.Join(" | ", names);
    }

    private static string WriteContext(ValidatedContract validated, string header)
    {
        var writer = new CodeWriter();
        WritePreamble(writer, header);

        var roots = validated.Operations
            .SelectMany(o => o.Definition.Responses.Select(r => r.Schema).Append(o.Definition.RequestSchema))
            .OfType<string>()
            .Select(name => validated.Contract.Schema(name).CSharpName)
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal);

        writer.Line("/// <summary>");
        writer.Line("/// Source-generated serialization metadata for the wire models. No reflection, and the options below");
        writer.Line("/// are fixed at compile time: duplicate properties refused, the discriminator read wherever it");
        writer.Line("/// appears, nullability annotations enforced, unknown members skipped.");
        writer.Line("/// </summary>");
        writer.Line("[JsonSourceGenerationOptions(");
        writer.Line("    AllowDuplicateProperties = false,");
        writer.Line("    AllowOutOfOrderMetadataProperties = true,");
        writer.Line("    AllowTrailingCommas = false,");
        writer.Line("    GenerationMode = JsonSourceGenerationMode.Metadata,");
        writer.Line("    MaxDepth = 64,");
        writer.Line("    NumberHandling = JsonNumberHandling.Strict,");
        writer.Line("    PropertyNameCaseInsensitive = false,");
        writer.Line("    ReadCommentHandling = JsonCommentHandling.Disallow,");
        writer.Line("    RespectNullableAnnotations = true,");
        writer.Line("    RespectRequiredConstructorParameters = true,");
        writer.Line("    UnmappedMemberHandling = JsonUnmappedMemberHandling.Skip)]");

        foreach (var root in roots)
        {
            writer.Line($"[JsonSerializable(typeof({root}))]");
        }

        writer.Open($"internal sealed partial class {ContextName} : JsonSerializerContext");
        writer.Close();

        return writer.ToString();
    }

    private static string WriteContract(ValidatedContract validated, string header)
    {
        var contract = validated.Contract;
        var writer = new CodeWriter();

        foreach (var line in header.Split('\n'))
        {
            writer.Line(line);
        }

        writer.Line();
        writer.Line($"namespace {Namespace};");
        writer.Line();
        writer.Line("/// <summary>");
        writer.Line("/// The facts about the contract that the handwritten runtime depends on, generated so that they cannot");
        writer.Line("/// drift from the snapshot: where the operations are, and the constants recorded in semantics.json.");
        writer.Line("/// </summary>");
        writer.Open($"internal static class {ContractClassName}");

        writer.Line("/// <summary>The contract this code was generated from.</summary>");
        writer.Line($"public const string Name = {CodeWriter.Literal(contract.Contract)};");
        writer.Line();
        writer.Line("/// <summary>The OpenAPI version the snapshot declares.</summary>");
        writer.Line($"public const string OpenApiVersion = {CodeWriter.Literal(contract.OpenApiVersion)};");
        writer.Line();
        writer.Line("/// <summary>The API version the snapshot declares in <c>info.version</c>.</summary>");
        writer.Line($"public const string ApiVersion = {CodeWriter.Literal(contract.ApiVersion)};");
        writer.Line();
        writer.Line("/// <summary>SHA-256 of the committed contract, <c>openapi.json</c>, as <c>provenance.json</c> records it.</summary>");
        writer.Line($"public const string SpecSha256 = {CodeWriter.Literal(contract.SnapshotSha256)};");
        writer.Line();
        writer.Line("/// <summary>The version of the generator that produced this code.</summary>");
        writer.Line($"public const int GeneratorVersion = {GeneratorVersion.ToString(CultureInfo.InvariantCulture)};");

        foreach (var operation in validated.Operations.OrderBy(o => o.Approval.ConstantName, StringComparer.Ordinal))
        {
            var name = operation.Approval.ConstantName;
            writer.Line();
            writer.Line($"/// <summary>The method of <c>{Xml(operation.Definition.Key.ToString())}</c>.</summary>");
            writer.Line($"public const string {name}Method = {CodeWriter.Literal(operation.Definition.Key.Method)};");
            writer.Line();
            writer.Line($"/// <summary>The path of <c>{Xml(operation.Definition.Key.ToString())}</c>.</summary>");
            writer.Line($"public const string {name}Path = {CodeWriter.Literal(operation.Definition.Key.Path)};");
        }

        foreach (var constant in contract.Constants.OrderBy(c => c.Name, StringComparer.Ordinal))
        {
            var name = Naming.ToPascalCase(constant.Name);
            writer.Line();
            writer.Line($"/// <summary>From semantics.json ({Xml(constant.Basis)}).</summary>");
            writer.Line(constant.Kind == System.Text.Json.JsonValueKind.String
                ? $"public const string {name} = {CodeWriter.Literal(constant.StringValue!)};"
                : $"public const int {name} = {checked((int)constant.IntegerValue!.Value).ToString(CultureInfo.InvariantCulture)};");
        }

        writer.Close();
        return writer.ToString();
    }

    /// <summary>XML-escapes text placed inside a doc comment.</summary>
    private static string Xml(string text)
        => Naming.Printable(text)
            .Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);

    private static void Require(bool condition, string what, string value)
    {
        if (!condition)
        {
            throw new InvalidDataException($"The {what} '{Naming.Printable(value)}' has a shape the generator does not write into a file header.");
        }
    }

    [GeneratedRegex("^[A-Za-z0-9][A-Za-z0-9.+-]{0,63}$")]
    private static partial Regex SafeToken();

    [GeneratedRegex("^[0-9a-f]{64}$")]
    private static partial Regex Sha256();
}
