<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Kkdev92.Jev.CodeGen</RootNamespace>
    <AssemblyName>Kkdev92.Jev.CodeGen</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

</Project>
